### ISSUE TITLE
Shell Build Error

### ISSUE THREAD

**Issue by oliveirawesley** [Ner3s/microfrontend-poc#1]
Hi @Ner3s ,

Do you know how can i solve this problem when running npm run build or npm run build:dev?

<img width="952" alt="Captura de Tela 2022-07-27 às 07 47 12" src="https://user-images.githubusercontent.com/39491341/181229203-dd811aaa-4606-47c9-a895-c7a7dff458bb.png">

**Comment by Ner3s** [comment]
Olá amigo,
Eu corrigi o bug, tenta atulizar a master.
Esse erro acontece quando não temos uma .env de prod no projeto e tentamos rodar o projeto, mas agora eu adicionei o build:dev no escopo global.
## 
Hey friend,
I fixed the bug, try to update master.
This error happens when we don't have a prod .env in the project and we try to run the project, but now I've added build:dev in the global scope.
